// NEON STICK RUN string table [zh-HK, en] — every UI string goes through cyber-kit i18n (localStorage cyber.lang).
import { i18n } from 'cyber-kit';
export const STAGE_NAMES = [
  ['天台熱身', 'ROOFTOP WARM-UP'], ['喉管小巷', 'PIPE ALLEY'], ['二段跳', 'DOUBLE UP'], ['無人機巡邏', 'DRONE PATROL'],
  ['激光圍欄', 'LASER FENCE'], ['飛簷走壁', 'WALL RUNNER'], ['飛索過海', 'GRAPPLE LINE'], ['崩塌天台', 'CRUMBLING ROOFS'],
  ['廣告牌森林', 'BILLBOARD JUNGLE'], ['九龍城寨', 'WALLED CITY'], ['暴雨狂奔', 'STORM SPRINT'], ['天際終點', 'SKYLINE FINALE'],
];
i18n.add({
  'doc.title': ['霓虹火柴人酷跑 NEON STICK RUN · 單手 3D 天台酷跑', 'NEON STICK RUN · one-thumb 3D rooftop parkour'],
  loading: ['霓虹四肢熱身中…', 'WARMING UP NEON LIMBS…'],
  kicker: ['NEON KOWLOON · 天台酷跑', 'NEON KOWLOON · ROOFTOP FREE-RUN'],
  title: ['霓虹火柴人酷跑', 'NEON STICK RUN'], titleEn: ['NEON STICK RUN', '霓虹火柴人酷跑'],
  tagline: ['喺落雨嘅九龍天台飛奔！一隻手指：撳／上掃＝跳（長按跳更高），下掃＝滑鏟，右掃＝衝刺撞爆無人機。', 'Free-run the rainy rooftops of Kowloon! One thumb: tap / swipe up = jump (hold for higher), swipe down = slide, swipe right = dash through drones.'],
  stages: ['關卡', 'STAGES'], stagesS: ['12 STAGES', '12 個關卡'], endless: ['無盡模式', 'ENDLESS'], endlessS: ['ENDLESS RUN · ENTER', '永無終點 · ENTER'],
  locker: ['霓虹衣櫃', 'NEON LOCKER'], lockerS: ['SKINS', '外觀'],
  bestDist: ['最遠', 'BEST'], starsTotal: ['星星', 'STARS'], chipsLbl: ['晶片', 'CHIPS'], privacy: ['私隱政策', 'Privacy policy'],
  touchHint: ['撳／上掃＝跳 · 長按＝跳高啲 · 半空再撳＝二段跳 · 下掃＝滑鏟 · 右掃＝衝刺', 'Tap / swipe ↑ = jump · hold = higher · tap again mid-air = double jump · swipe ↓ = slide · swipe → = dash'],
  keysHint: ['<kbd>Space</kbd>/<kbd>↑</kbd> 跳（按住更高）　<kbd>↓</kbd> 滑鏟　<kbd>→</kbd>/<kbd>Shift</kbd> 衝刺　<kbd>P</kbd> 暫停　<kbd>M</kbd> 靜音', '<kbd>Space</kbd>/<kbd>↑</kbd> jump (hold = higher)　<kbd>↓</kbd> slide　<kbd>→</kbd>/<kbd>Shift</kbd> dash　<kbd>P</kbd> pause　<kbd>M</kbd> mute'],
  back: ['返回', 'BACK'], backS: ['BACK', '返回'], selectStage: ['揀關卡', 'SELECT STAGE'], stageN: ['第 {n} 關', 'STAGE {n}'], stageTag: ['第 {n} 關', 'STAGE {n}'],
  locked: ['未解鎖', 'LOCKED'], trialLock: ['試玩只開放第 1–3 關', 'Trial: stages 1–3 only'], bestTime: ['最佳 {t}', 'BEST {t}'],
  wallet: ['晶片 {n}', '{n} CHIPS'], colours: ['霓虹顏色', 'NEON COLOUR'], trails: ['光軌', 'TRAIL'], equip: ['使用', 'EQUIP'], equipped: ['使用中', 'EQUIPPED'], buy: ['{p} 晶片', '{p} CHIPS'],
  bought: ['已購買：{name}', 'Unlocked: {name}'], tooPoor: ['晶片唔夠（仲差 {n}）', 'Not enough chips (need {n} more)'], lockerNote: ['用晶片解鎖純裝飾外觀，唔影響遊戲平衡。', 'Chips unlock cosmetic looks only — no gameplay advantage.'],
  dist: ['距離', 'DIST'], chips: ['晶片', 'CHIPS'], time: ['時間', 'TIME'], speed: ['速度', 'SPEED'],
  pauseTip: ['暫停 (P / Esc)', 'Pause (P / Esc)'], muteTip: ['靜音 (M)', 'Mute (M)'],
  paused: ['已暫停', 'PAUSED'], pausedS: ['PAUSED', '已暫停'], resume: ['繼續', 'RESUME'], resumeS: ['RESUME · P', 'P'], restart: ['重新開始', 'RESTART'], restartS: ['RESTART', '重新開始'], quit: ['離開', 'QUIT'], quitS: ['MAIN MENU', '主畫面'],
  go: ['出發！', 'GO!'], goS: ['RUN!', '跑！'], endlessBanner: ['無盡模式', 'ENDLESS RUN'], endlessNote: ['速度會不斷提升 —— 睇你跑得幾遠', 'Speed keeps rising — how far can you go?'],
  clear: ['完成！', 'CLEAR!'], fail: ['失手…', 'WIPEOUT…'], gameOver: ['遊戲結束', 'GAME OVER'], newBest: ['★ 新紀錄 ★', '★ NEW RECORD ★'],
  sDist: ['距離', 'Distance'], sTime: ['時間', 'Time'], sChips: ['晶片', 'Chips'], sScore: ['分數', 'Score'], sStyle: ['花式', 'Style'], sSpeed: ['最高速', 'Top speed'],
  next: ['下一關', 'NEXT STAGE'], nextS: ['NEXT · ENTER', 'ENTER'], retry: ['再跑一次', 'RETRY'], retryS: ['RETRY · ENTER', 'ENTER'], menu: ['主畫面', 'MAIN MENU'], menuS: ['MAIN MENU', '主畫面'], stagesBtn: ['關卡列表', 'STAGE LIST'],
  revive: ['原地復活', 'REVIVE'], reviveAd: ['睇廣告 · 每局一次', 'WATCH AD · ONCE PER RUN'], reviveFree: ['免費 · 每局一次', 'FREE · ONCE PER RUN'], revived: ['復活！', 'REVIVED!'],
  c_fell: ['跌落街', 'FELL TO THE STREET'], c_wall: ['撞牆', 'HIT A WALL'], c_laser: ['觸碰激光', 'ZAPPED BY A LASER'], c_drone: ['撞到無人機', 'HIT BY A DRONE'], c_pipe: ['撞到喉管', 'HIT A PIPE'], c_board: ['撞到廣告牌', 'HIT A BILLBOARD'],
  starsGot: ['{n} / 3 星', '{n} / 3 STARS'], starRule: ['★ 完成 · ★★ 晶片 ≥ 50% · ★★★ 晶片 ≥ 80% 兼冇復活', '★ clear · ★★ chips ≥ 50% · ★★★ chips ≥ 80% and no revive'],
  milestone: ['{m} 米！', '{m} M!'], milestoneS: ['+25 晶片 · 新區域', '+25 CHIPS · NEW DISTRICT'],
  allClear: ['全部 12 關完成！無盡模式等緊你', 'All 12 stages cleared! Endless mode awaits'],
  p_magnet: ['磁石', 'MAGNET'], p_shield: ['護盾', 'SHIELD'], p_slow: ['慢鏡', 'SLOW-MO'],
  vault: ['跨越', 'VAULT'], wallrun: ['走壁', 'WALL RUN'], swing: ['擺盪', 'SWING'], smash: ['撞爆！', 'SMASH!'], shieldUsed: ['護盾抵擋！', 'SHIELD SAVED YOU!'],
  gJump: ['跳 · 長按更高', 'JUMP · HOLD'], gJumpK: ['撳 / 上掃', 'TAP / ↑'], gSlide: ['滑鏟', 'SLIDE'], gDash: ['衝刺 · 撞爆', 'DASH · SMASH'], gSlideK: ['下掃', 'SWIPE ↓'], gDashK: ['右掃', 'SWIPE →'],
  // first-time tips
  h_jump: ['撳 或 上掃 = 跳 · 長按跳得更高', 'Tap or swipe ↑ = jump · hold for a higher jump'],
  h_pipe: ['下掃 = 滑鏟穿過喉管', 'Swipe ↓ = slide under pipes'], h_board: ['下掃滑過 · 或右掃衝刺撞爛廣告牌', 'Slide under — or swipe → to dash through billboards'],
  h_gapWide: ['大罅：半空再撳 = 二段跳', 'Wide gap: tap again mid-air = double jump'], h_drone: ['右掃衝刺 = 撞爆無人機', 'Swipe → to dash and smash drones'],
  h_laser: ['跳過激光圍欄', 'Jump over laser fences'], h_wall: ['跳向廣告牆會自動走壁 · 撳 = 蹬牆跳', 'Jump at the billboard wall to wall-run · tap = wall-jump'],
  h_grap: ['跳近鈎點會自動擺盪 · 撳 = 提早放手', 'Jump near a hook to swing · tap = let go early'], h_collapse: ['崩塌天台：落地即跳，唔好停！', 'Crumbling roofs: keep moving and jump!'],
  h_vault: ['矮箱會自動跨越', 'Low crates are vaulted automatically'],
  // hub / trial
  trialTag: ['試玩 · 第 1–3 關 · 無盡 800 米', 'TRIAL · stages 1–3 · endless 800 m'], trialLeft: ['今日仲有 {n} 次試玩', '{n} trial runs left today'],
  trialTitle: ['試玩完結', 'TRIAL COMPLETE'], trialBody: ['試玩只包括第 1–3 關同無盡模式頭 800 米。返大廳解鎖銀級，就可以玩晒 12 關同無限無盡模式（包括日後加入銀級嘅所有新遊戲）。', 'The trial covers stages 1–3 and the first 800 m of endless. Unlock Silver in the hub to get all 12 stages and unlimited endless (plus every future game added to Silver).'],
  toHub: ['返大廳解鎖', 'UNLOCK IN HUB'], toHubS: ['BACK TO ARCADE', '返回大廳'], silver: ['銀級遊戲', 'SILVER GAME'],
});
